$content = Get-Content 'lib\screens\admin\admin_dashboard_screen.dart'
$content = $content -replace 'if \(post\.imageUrl\.isNotEmpty\)', '// if (false) // Fixed orphaned code'
$content = $content -replace 'post\.imageUrl,', '"", // post.imageUrl,'
$content = $content -replace 'post\.authorName', '"Unknown Author"'
$content = $content -replace 'post\.createdAt', 'DateTime.now()'
$content = $content -replace 'post\.viewCount', '0'
$content = $content -replace 'post\.commentCount', '0'
$content = $content -replace 'post\.likes\.length', '0'
$content = $content -replace 'post\.dislikes\.length', '0'
$content = $content -replace 'await _updateBlogPost\(\s*post,', 'return; // await _updateBlogPost('
$content | Set-Content 'lib\screens\admin\admin_dashboard_screen.dart' 